apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tobibrws2-nodejs-gitops
  description: This is GitOps manifest for tobibrws2-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=tobibrws2-nodejs
    backstage.io/kubernetes-id: tobibrws2-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tobibrws2-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tobibrws2-nodejs
